/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Arthur
 */
public class Jframe_GPU extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_GPU
     */
    public Jframe_GPU() {
        initComponents();
        
        // DEIXANDO NOSSA MENSAGEM DE FEEDBACK OCULTA INICIALMENTE //
        varMsg.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        Atividade = new javax.swing.JLabel();
        Uso = new javax.swing.JLabel();
        Temperatura = new javax.swing.JLabel();
        Overclock = new javax.swing.JLabel();
        varModelo = new javax.swing.JLabel();
        varAtividade = new javax.swing.JLabel();
        varUso = new javax.swing.JLabel();
        varTemperatura = new javax.swing.JLabel();
        varOverclock = new javax.swing.JLabel();
        varMsg = new javax.swing.JLabel();
        ButtonLigarpc = new javax.swing.JButton();
        ButtonDesligarpc = new javax.swing.JButton();
        ButtonIniciarjogo = new javax.swing.JButton();
        ButtonFinalizarjogo = new javax.swing.JButton();
        ButtonOverclock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setText("MONITORAMENTO DE GPU");
        Titulo.setToolTipText("");

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Modelo.setText("MODELO:");

        Atividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Atividade.setText("ATIVIDADE:");

        Uso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uso.setText("USO:");

        Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Temperatura.setText("TEMPERATURA:");

        Overclock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Overclock.setText("OVERCLOCK:");

        varModelo.setText("GTX 1650 TI 4Gb");

        varAtividade.setText("Desligada");

        varUso.setText("0");

        varTemperatura.setText("25");

        varOverclock.setText("Desativado");

        varMsg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        varMsg.setForeground(new java.awt.Color(255, 0, 0));
        varMsg.setText("...");

        ButtonLigarpc.setText("Ligar PC");
        ButtonLigarpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLigarpcActionPerformed(evt);
            }
        });

        ButtonDesligarpc.setText("Desligar PC");
        ButtonDesligarpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDesligarpcActionPerformed(evt);
            }
        });

        ButtonIniciarjogo.setText("Iniciar jogo");
        ButtonIniciarjogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarjogoActionPerformed(evt);
            }
        });

        ButtonFinalizarjogo.setText("Finalizar Jogo");
        ButtonFinalizarjogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFinalizarjogoActionPerformed(evt);
            }
        });

        ButtonOverclock.setText("Ativar overclock");
        ButtonOverclock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOverclockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Temperatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(varTemperatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonFinalizarjogo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Overclock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(varOverclock)
                        .addGap(222, 222, 222)
                        .addComponent(varMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonOverclock))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Atividade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(varAtividade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Modelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(varModelo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Uso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(varUso)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonLigarpc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonDesligarpc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonIniciarjogo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Titulo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo)
                    .addComponent(varModelo)
                    .addComponent(ButtonLigarpc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atividade)
                    .addComponent(varAtividade)
                    .addComponent(ButtonDesligarpc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uso)
                    .addComponent(varUso)
                    .addComponent(ButtonIniciarjogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperatura)
                    .addComponent(varTemperatura)
                    .addComponent(ButtonFinalizarjogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Overclock)
                    .addComponent(varOverclock)
                    .addComponent(varMsg)
                    .addComponent(ButtonOverclock))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // INSTANCIANDO UMA NOVA GPU USANDO O MÉTODO CONSTRUTOR //
    GPU g1 = new GPU("GTX", 16, 50, "TI", 4);
    
    private void ButtonLigarpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLigarpcActionPerformed
        
        // MÉTODO CONFIGURADO NA CLASSE GPU PARA LIGAR O PC //
        g1.ligarpc();
        
        // MÉTODO PARA MUDAR O TEXTO DA MENSAGEM, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varMsg.setText(g1.getMsg());
        
        // MÉTODO PARA MUDAR O TEXTO DA ATIVIDADE, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varAtividade.setText(g1.getAtividade());
        
        // MÉTODO PARA MUDAR O TEXTO DA TEMPERATURA, QUE É ARMAZENADO COMO INT //
        varTemperatura.setText(Integer.toString(g1.getTemperatura()));
        
        // MÉTODO PARA MUDAR O TEXTO DO USO, QUE É ARMAZENADO NA PROPRIA CLASE COMO INT //
        varUso.setText(Integer.toString(g1.getUso()));
        
        
        // MÉTODO PARA EXIBIR A MENSAGEM QUE ESTAVA OCULTA POR PADRAO //
        varMsg.setVisible(true);
        
        // CRIANDO OBJETO TIMER PARA FAZER A MENSAGEM SUMIR DEPOIS DE 2 SEGUNDOS //
        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {varMsg.setVisible(false);});
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ButtonLigarpcActionPerformed

    private void ButtonDesligarpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDesligarpcActionPerformed
        
        // MÉTODO CONFIGURADO NA CLASSE GPU PARA DESLIGAR O PC //
        g1.desligarpc();
        
        // MÉTODO PARA MUDAR O TEXTO DA MENSAGEM, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varMsg.setText(g1.getMsg());
        
        // MÉTODO PARA MUDAR O TEXTO DA ATIVIDADE, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varAtividade.setText(g1.getAtividade());
        
        // MÉTODO PARA MUDAR O TEXTO DA TEMPERATURA, QUE É ARMAZENADO COMO INT //
        varTemperatura.setText(Integer.toString(g1.getTemperatura()));
        
        // MÉTODO PARA MUDAR O TEXTO DO USO, QUE É ARMAZENADO NA PROPRIA CLASE COMO INT //
        varUso.setText(Integer.toString(g1.getUso()));
        
        
        // MÉTODO PARA EXIBIR A MENSAGEM QUE ESTAVA OCULTA POR PADRAO //
        varMsg.setVisible(true);
        
        // CRIANDO OBJETO TIMER PARA FAZER A MENSAGEM SUMIR DEPOIS DE 2 SEGUNDOS //
        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {varMsg.setVisible(false);});
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ButtonDesligarpcActionPerformed

    private void ButtonIniciarjogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarjogoActionPerformed
        
        // MÉTODO CONFIGURADO NA CLASSE GPU PARA DESLIGAR O PC //
        g1.iniciarjogo();
        
        // MÉTODO PARA MUDAR O TEXTO DA MENSAGEM, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varMsg.setText(g1.getMsg());
        
        // MÉTODO PARA MUDAR O TEXTO DA ATIVIDADE, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varAtividade.setText(g1.getAtividade());
        
        // MÉTODO PARA MUDAR O TEXTO DA TEMPERATURA, QUE É ARMAZENADO COMO INT //
        varTemperatura.setText(Integer.toString(g1.getTemperatura()));
        
        // MÉTODO PARA MUDAR O TEXTO DO USO, QUE É ARMAZENADO NA PROPRIA CLASE COMO INT //
        varUso.setText(Integer.toString(g1.getUso()));
        
        
        // MÉTODO PARA EXIBIR A MENSAGEM QUE ESTAVA OCULTA POR PADRAO //
        varMsg.setVisible(true);
        
        // CRIANDO OBJETO TIMER PARA FAZER A MENSAGEM SUMIR DEPOIS DE 2 SEGUNDOS //
        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {varMsg.setVisible(false);});
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ButtonIniciarjogoActionPerformed

    private void ButtonFinalizarjogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFinalizarjogoActionPerformed
        
        // MÉTODO CONFIGURADO NA CLASSE GPU PARA DESLIGAR O PC //
        g1.finalizarjogo();
        
        // MÉTODO PARA MUDAR O TEXTO DA MENSAGEM, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varMsg.setText(g1.getMsg());
        
        // MÉTODO PARA MUDAR O TEXTO DA ATIVIDADE, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varAtividade.setText(g1.getAtividade());
        
        // MÉTODO PARA MUDAR O TEXTO DA TEMPERATURA, QUE É ARMAZENADO COMO INT //
        varTemperatura.setText(Integer.toString(g1.getTemperatura()));
        
        // MÉTODO PARA MUDAR O TEXTO DO USO, QUE É ARMAZENADO NA PROPRIA CLASE COMO INT //
        varUso.setText(Integer.toString(g1.getUso()));
        
        
        // MÉTODO PARA EXIBIR A MENSAGEM QUE ESTAVA OCULTA POR PADRAO //
        varMsg.setVisible(true);
        
        // CRIANDO OBJETO TIMER PARA FAZER A MENSAGEM SUMIR DEPOIS DE 2 SEGUNDOS //
        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {varMsg.setVisible(false);});
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ButtonFinalizarjogoActionPerformed

    private void ButtonOverclockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOverclockActionPerformed
        g1.changeOverclock();
        
        // MÉTODO PARA MUDAR O TEXTO DA MENSAGEM, QUE É ARMAZENADO NA PROPRIA CLASE COMO STRING //
        varMsg.setText(g1.getMsg());
        
        // MÉTODO PARA EXIBIR A MENSAGEM QUE ESTAVA OCULTA POR PADRAO //
        varMsg.setVisible(true);
        
        // CRIANDO OBJETO TIMER PARA FAZER A MENSAGEM SUMIR DEPOIS DE 2 SEGUNDOS //
        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {varMsg.setVisible(false);});
        timer.setRepeats(false);
        timer.start();
        
        // MUDANDO O TEXTO DO ATRIBUTO //
        varOverclock.setText(g1.getOverclock());
        
        // MUDANDO O TEXTO DO BOTÃO //
        if ("Ativado".equals(g1.getOverclock())) {
            ButtonOverclock.setText("Desativar overclock.");
        } else {
            ButtonOverclock.setText("Ativar overclock");
        }
        
    }//GEN-LAST:event_ButtonOverclockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_GPU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_GPU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_GPU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_GPU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_GPU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atividade;
    private javax.swing.JButton ButtonDesligarpc;
    private javax.swing.JButton ButtonFinalizarjogo;
    private javax.swing.JButton ButtonIniciarjogo;
    private javax.swing.JButton ButtonLigarpc;
    private javax.swing.JButton ButtonOverclock;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Overclock;
    private javax.swing.JLabel Temperatura;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Uso;
    private javax.swing.JLabel varAtividade;
    private javax.swing.JLabel varModelo;
    private javax.swing.JLabel varMsg;
    private javax.swing.JLabel varOverclock;
    private javax.swing.JLabel varTemperatura;
    private javax.swing.JLabel varUso;
    // End of variables declaration//GEN-END:variables
}
